sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  wechat:
    appid: wx0805e4ce219781e0
    secret: e338660e9ab351ed12ea39665e59cc0e
  alioss:
    endpoint: oss-cn-qingdao.aliyuncs.com
    access-key-id: LTAI5tRqNf5HmrE8iT24br6J
    access-key-secret: qSg26ZQHcMbHK0NH2SUzOP1E3VgdwH
    bucket-name: waimai-7758
  redis:
    host: 192.168.242.128
    port: 6379
    password: 111111
    database: 0