sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-qingdao.aliyuncs.com
    access-key-id: LTAI5tRqNf5HmrE8iT24br6J
    access-key-secret: qSg26ZQHcMbHK0NH2SUzOP1E3VgdwH
    bucket-name: waimai-7758